name: Deploy React App to S3

on:
  push:
    branches:
      - main  # You can change this to your target branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.0.0'  # Use the Node.js version your app requires

      - name: Update Browserslist DB
        run: npx update-browserslist-db@latest

      - name: Build
        run: CI=false npm run build

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync ./build s3://$AWS_BUCKET_NAME --delete --region $AWS_REGION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # - name: Invalidate CloudFront cache (Optional)
      #   if: ${{ secrets.DISTRIBUTION_ID != '' }}
      #   run: |
      #     aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
